server:
  port: ${PORT:8081}
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://mongo:123@localhost:27017/cooperativism-voting}
      auto-index-creation: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    virtual-host: ${RABBITMQ_VHOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBBITMQ_PASSWORD:guest}
    queue:
      name: closed-schedule-vote-results
client:
  service:
    cpf: https://user-info.herokuapp.com/users/
scheduler:
  enabled: true